codemod-js/codemod

.travis.yml
package.json

This will allow us to cut releases automatically based on commit messages.

chore: configure package for semantic-release

---

src/TransformRunner.ts
tslint.json

This also fixes the errors it found.

chore: enable `no-unused-variable` tslint rule

---

package.json
src/Options.ts
test/OptionsTest.ts

Closes #4 
cc @kentcdodds @alexhancock

feat: process source paths as globs

---

src/TransformRunner.ts
test/TransformRunnerTest.ts

Pass filename to babel so plugins have access to it.

---

.gitignore
.yarnrc
bin/codemod
package.json
src/Options.ts
src/index.ts
test/CLITest.ts
test/OptionsTest.ts
test/fixtures/plugin/increment.js
yarn.lock

refactor: add cli tests

---

README.md

Thought we should link to help, for until we make progress on #29. Feel free to close this if you feel it's unnecessary.
I can squash the commits if this repo doesn't have squash-merge enabled!

Link to help on setting up babel-register

---

package.json
yarn.lock

Greenkeeper/mocha 4.0.1

---

.prettierrc
.travis.yml
package.json
script/.editorconfig
script/prettier-check
src/Options.ts
src/TransformRunner.ts
src/index.ts
src/iterateSources.ts
test/CLITest.ts
test/OptionsTest.ts
test/TransformRunnerTest.ts
yarn.lock

Addresses #54 
What do you think, @mcMickJuice?

style: add prettier and reformat on commit

---

.gitignore
commitlint.config.js

This was accidentally gitignored, but I didn't realize it.

style(commitlint): add missing config file

---

package.json
yarn.lock

https://github.com/frontsideair/yarnhook

chore(yarn): enable `yarnhook` to run yarn on various git operations

---

src/CLIEngine.ts
src/Config.ts
src/Options.ts
src/index.ts
test/cli/CLITest.ts
test/unit/ConfigTest.ts
test/unit/OptionsTest.ts

Hopefully this will pave the way for making #107 easier.

Refactor config & CLI code

---

src/AllSyntaxPlugin.ts
src/BabelPluginTypes.ts
src/CLIEngine.ts
src/Config.ts
src/InlineTransformer.ts
src/PrettierPrinterPlugin.ts
src/RecastPlugin.ts
src/TransformRunner.ts
src/Transformer.ts
src/index.ts
test/unit/InlineTransformer.ts
test/unit/TransformRunnerTest.ts

This will make it easier to do parallel transformations.

Refactor runner

---

.travis.yml

https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98

chore(ci): use npm to globally install greenkeeper-lockfile

---

test/unit/InlineTransformerTest.ts

Issue #157 says that this is happening with babel-codemod, but I can't reproduce it in a test. Also, this whole test file wasn't running! Renaming it to end in "Test" fixes that.

test: add a regression test for extra semicolons

---

packages/cli/src/Config.ts
packages/cli/test/cli/CLITest.ts

fix: ignore `.d.ts` files

---

packages/cli/package.json

Maybe this will fix the broken travis publish step?

chore(package): set publish config registry

---

.circleci/config.yml
lerna.json
package.json
packages/cli/package.json
yarn.lock

I am trying to transition this repository to a monorepo, but I cannot figure out how to do so while keeping publishing using [semantic-release]. There is a [semantic-release-monorepo] project, but it didn't seem to work when I tried it. There's also [lerna-semantic-release], an abandoned fork of [lerna].
So instead I'm giving up and just going to do releases manually. For now this means that:
- new versions will be published by my npm user
- comments on PRs and issues that were closed as part of a release will probably not be included
- release notes will be sparser/absent
[semantic-release]: https://github.com/semantic-release/semantic-release
[semantic-release-monorepo]: https://github.com/Updater/semantic-release-monorepo
[lerna-semantic-release]: …

Manual release

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/src/BabelPluginTypes.ts
packages/matchers/package.json
packages/parser/CHANGELOG.md
packages/parser/package.json
packages/parser/src/__tests__/test.ts
packages/parser/src/index.ts
packages/parser/src/options.ts
yarn.lock

- `placeholders`
- `logicalAssignment`
- `partialApplication`

fix: add more parsing plugins

---

packages/cli/package.json
packages/core/package.json
packages/matchers/package.json
packages/parser/package.json

Enables intellisense in Webstorm/IntelliJ.

Add "types" to package.json

---

.circleci/config.yml
package.json
packages/cli/package.json
packages/core/package.json
packages/matchers/package.json
packages/parser/package.json
yarn.lock

This should happen automatically whenever changes are committed.

chore(package): reorder package.json

---

CONTRIBUTING.md
packages/cli/LICENSE.txt
packages/core/LICENSE.txt
packages/matchers/LICENSE.txt
packages/parser/LICENSE.txt

This hasn't been a Square project for a while.

fix(license): update outdated license files

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/matchers/CHANGELOG.md
packages/matchers/package.json
packages/parser/CHANGELOG.md
packages/parser/package.json

- @codemod/cli@2.1.10
- @codemod/core@1.0.2
- @codemod/matchers@1.0.5
- @codemod/parser@1.0.3

chore(publish): publish new versions

---

package.json
packages/cli/package.json
packages/core/package.json
packages/matchers/package.json
packages/parser/package.json
yarn.lock

Add dependencies to the packages that actually use them.

chore(package): clean up dependencies

---

packages/cli/script/_commands/ci.ts
packages/core/script/_commands/ci.ts
packages/matchers/script/_commands/ci.ts
packages/parser/script/_commands/ci.ts

test(ci): add color back

---

packages/cli/test/cli/CLITest.ts

The error message changed in node v12.

test: fix test expectation

---

.circleci/config.yml
yarn.lock

Not sure how this happened. Adding `--frozen-lockfile` to `yarn install` to hopefully keep it from happening again.

chore: re-sync yarn.lock

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/matchers/CHANGELOG.md
packages/matchers/package.json

- `@codemod/cli` v2.1.11
- `@codemod/matchers` v1.0.6

chore: publish new versions of packages

---

packages/cli/package.json
packages/core/package.json
packages/matchers/package.json
packages/parser/package.json

- `@codemod/cli` v2.1.13
- `@codemod/core` v1.0.4
- `@codemod/matchers` v1.0.8
- `@codemod/parser` v1.0.5

chore(publish): publish new version

---

packages/cli/package.json

@codemod/cli@2.2.0

---

packages/cli/src/Config.ts

fix(cli): ignore node modules directories

---

packages/cli/package.json
packages/cli/src/resolvers/AstExplorerResolver.ts
packages/cli/test/unit/resolvers/AstExplorerResolverTest.ts
yarn.lock

fix(cli): account for `/latest` astexplorer URLs

---

.eslintrc
package.json
packages/cli/package.json
packages/cli/script/_commands/ci.ts
packages/cli/src/resolvers/AstExplorerResolver.ts
packages/cli/src/resolvers/NetworkResolver.ts
packages/cli/test/helpers/TestServer.ts
packages/core/script/_commands/ci.ts
packages/matchers/script/_commands/ci.ts
packages/matchers/src/NodeTypes.ts
packages/matchers/src/matchers.ts
packages/matchers/src/matchers/capture.ts
packages/matchers/src/matchers/tupleOf.ts
packages/parser/script/_commands/ci.ts
packages/parser/src/__tests__/test.ts
yarn.lock

Also removes the JUnit reporting stuff and removes the whatwg-url package in favor of the built-in `URL`.

build: update dev deps

---

packages/matchers/package.json
packages/matchers/src/matchers.ts

This should have happened with #900.

feat(matchers): rebuild `matchers.ts`

---

.husky/pre-commit
package.json
packages/cli/package.json
packages/matchers/src/__tests__/matchers.test.ts
packages/matchers/src/matchers/generated.ts
packages/rebuild-matchers/src/utils/git.ts
packages/rebuild-matchers/src/utils/rebuild.ts
pnpm-lock.yaml

fix(matchers): remove `null` prop special case
