codemod-js/codemod

- src/Options.ts
- src/TransformRunner.ts
- src/index.ts
- test/OptionsTest.ts
- test/fixtures/plugin/index.js
Previously the basename of the resolved plugin file would be used as the plugin name when applying options. However, that meant that if the file was called "index.js" in the plugin package, i.e. named "my-codemod", it was distributed with, the plugin options would have to be given to a plugin named "index" rather than "my-codemod".
> fix: ensure plugin option association

- src/TransformRunner.ts
- test/TransformRunnerTest.ts
There may be a `.babelrc` file in the project where `codemod` is run, but it should not pick up its contents and use the plugins/presets it defines when running. For some reason this wasn't an issue in v1.1.2, but showed up in v1.1.3.
> fix: ignore ambient babelrc config files

- .travis.yml
node v7 is no longer supported, so let's replace it with v9.
> test(ci): build with node 6, 8, and 9

- src/index.ts
- yarn.lock
This updates to the latest version within the declared ranges in package.json. `tslint` now warns about unread variables, so I fixed the one instance of that in the codebase.
> chore(package): upgrade all dependencies

- src/TransformRunner.ts
Without the `decorators` plugin specified, running a codemod chokes on any decorator in the source being transformed. Without a way to specify a custom list of plugins, we need to add it to the hardcoded list.
> Support decorators when transforming source

- README.md
- package.json
- src/Options.ts
- src/index.ts
- test/CLITest.ts
- test/OptionsTest.ts
- test/fixtures/plugin/increment-export-default-multiple/increment-export-default.js
- test/fixtures/plugin/increment-export-default-multiple/increment-value.js
- test/fixtures/plugin/increment-export-default.js
- yarn.lock
https://github.com/square/babel-codemod/issues/29
Points of discussion/questions:
* Not sure of naming of this cli option
* How can we write a unit test against this?
> Adds option for running plugin through babel-preset-env pipeline

- package.json
This allows us to avoid running the tests twice, once when running `yarn install` and once when running `yarn test`.
> chore(package): use the `prepublishOnly` script instead of `prepublish`

- src/TransformRunner.ts
- src/index.ts
This simplifies the control flow and puts most of the code into an `async` function, allowing us to make better use of `await`.
> refactor(runner): get rid of the runner delegate

- CONTRIBUTING.md
- README.md
- package.json
- script/prettier-check
- src/Options.ts
- src/PluginLoader.ts
- src/index.ts
- src/resolvers/AstExplorerResolver.ts
- src/resolvers/FileSystemResolver.ts
- src/resolvers/NetworkResolver.ts
- src/resolvers/PackageResolver.ts
- src/resolvers/Resolver.ts
- test/cli/CLITest.ts
- test/fixtures/astexplorer/default.json
- test/fixtures/plugin/increment.js
- test/mocha.opts
- test/unit/OptionsTest.ts
- test/unit/TestServer.ts
- test/unit/TransformRunnerTest.ts
- test/unit/resolvers/AstExplorerResolverTest.ts
- test/unit/resolvers/FileSystemResolverTest.ts
- test/unit/resolvers/NetworkResolverTest.ts
- tsconfig.json
- tslint.json
- yarn.lock
Begins work on #33.
@hzoo, what do you think of the proposed `--remote-plugin` option in this PR's README? I made it different from `--plugin` out of concern for security. I also think the implementation should probably make you confirm somehow before actually loading it.
---
**TODO:**
> Run from AST Explorer

- src/index.ts
- test/cli/CLITest.ts
`codemod` now prints all files it runs with, but dims those where there are no changes. This is similar to what prettier does. In addition, it prints the number of milliseconds taken to process each file.
> feat(display): improve the informational output when running the CLI

- .travis.yml
This will allow us to detect issues with dependency drift, i.e. in-range dependencies that break the build.
> test(ci): if running with cron ignore the lockfile

- package.json
- src/transpile-requires.ts
- yarn.lock
v7.0.0-beta.41 added `assertVersion` and a wrapper around each plugin that checks the babel API version. Since we were manually loading the presets here we weren't supplying the babel API. Using just the preset names means that babel will load them for us and everything should work as expected.
https://github.com/babel/babel/commit/a4795408b47e713aa2635d54197343be77e30f35#diff-b4beead8ad9195361b4537601cc22532
> fix(babel): let babel load the presets

- src/transpile-requires.ts
If you simply pass package names into babel's list of presets then it'll try to load them from the working directory. That doesn't work for us, so we need to resolve–but not load!–the presets relative to babel-codemod itself.
Fixes #102
> fix: use our versions of the presets for transpiling

- src/AllSyntaxPlugin.ts
- src/Options.ts
- src/RecastPlugin.ts
- src/TransformRunner.ts
- src/transpile-requires.ts
When transpiling required files we need to be pretty liberal about what syntax we allow, otherwise we can end up in a situation where the current node version can actually parse more natively than babylon is allowed to by `@babel/preset-env`. This should fix that.
Fixes #102 
cc @RIP21
> fix: use all syntax plugins

- src/CLIEngine.ts
- test/cli/CLITest.ts
- test/fixtures/plugin/bad-plugin.js
I neglected to preserve the call to `onTransform` in error cases.
> fix: ensure plugin errors are printed

- src/Config.ts
- src/Options.ts
- src/index.ts
- test/unit/OptionsTest.ts
This makes it easier to do one-off addition of extensions rather than having to hardcode the default values everywhere you want to include more.
> feat(cli): allow adding extensions rather than replacing them all

- src/index.ts
- tsconfig.json
The default value was not properly being shown, and there was no example showing what alternate printers there were (such as `prettier`).
> fix(cli): add better help output describing `--printer`

- .travis.yml
- test/unit/OptionsTest.ts
We may want to drop node v6 at some point, but there's not compelling reason to right now.
> test(ci): test with node v10

- src/PrettierPrinterPlugin.ts
Prettier warns when it does not have a parser or filepath because it can't know what type of code it is that it should be reformatting. This silences that warning by providing prettier with the filepath to process so it can automatically determine which parser to use.
> fix(prettier): silence parser warning

- src/resolvers/AstExplorerResolver.ts
- test/unit/resolvers/AstExplorerResolverTest.ts
Since astexplorer.net doesn't force SSL, users might be using it without SSL. When they copy the URL, it'll be `http` instead of `https`. We now accept such URLs, but turn them into `https` when normalizing them.
> fix(astexplorer): accept non-SSL URLs

- README.md
- src/AllSyntaxPlugin.ts
- src/BabelPluginTypes.ts
- src/Config.ts
- src/Options.ts
- src/RecastPlugin.ts
- src/extensions.ts
- src/index.ts
- src/resolvers/FileSystemResolver.ts
- src/transpile-requires.ts
- test/cli/CLITest.ts
- test/fixtures/plugin/replace-any-with-object.ts
- test/unit/ConfigTest.ts
- test/unit/OptionsTest.ts
- tsconfig.json
To support TypeScript, mostly we just needed to use the `typescript` parser plugin when the file being processed is TypeScript.
BREAKING CHANGE: This expands the set of file extensions that babel-codemod will look for to include `.ts`, `.tsx`, `.es`, `.es6`, and `.mjs` in addition to `.js` and `.jsx`.
Closes #137
> feat(typescript): process TypeScript files

- package.json
- yarn.lock
There was some sort of incompatibility between the type declarations for node and rxjs around the modified for an `observable` property.  Upgrading lint-staged seems to fix it, so that's what I'm doing here.
> chore(package): upgrade lint-staged to fix type checking

- src/AllSyntaxPlugin.ts
- src/BabelPluginTypes.ts
- yarn.lock
This version requires a new option to be passed to the decorators plugin to determine where decorators go with respect to the `export` keyword.  See https://github.com/tc39/proposal-decorators/issues/69 for more information.
> fix(package): upgrade babel to rc.2

- package.json
- yarn.lock
This PR updates to the stable version of Babel 7.0.0. After updating, I ran the tests, which all still passed. Were there any breaking changes in [7.0.0-rc.4](https://github.com/babel/babel/releases/tag/v7.0.0-rc.4) that need to be considered in this update that I can help out with?
> chore(package): update to stable version of babel 7

- package.json
This change was done using `husky-upgrade`.
> chore(husky): move hooks to `husky.hook`

- src/AllSyntaxPlugin.ts
- src/Config.ts
- src/InlineTransformer.ts
- src/Options.ts
- src/index.ts
- src/transpile-requires.ts
- test/cli/CLITest.ts
Previously babel-codemod hardcoded a value of `module` for the source type when parsing. This meant that any code not valid in strict mode could not be processed. Now babel-codemod uses a default source type of `unambiguous`, which means that babel will try to infer the source type. Additionally, this source type can be overridden with the `--source-type` option.
Closes #175
> feat: let babel guess the source type

- package.json
Since we import it directly we must depend on it directly, since without this the install may not work with some `node_modules` layouts (i.e. pnpm).
> fix: explicitly depend on `@babel/parser`

- packages/cli/bin/codemod
- packages/cli/src/CLIEngine.ts
- packages/cli/src/System.ts
- packages/cli/src/index.ts
- packages/cli/src/iterateSources.ts
- packages/cli/test/helpers/runCodemodCLI.ts
This shamelessly copies the idea from the TypeScript compiler API, and will hopefully allow use with virtual file systems (like browser or nodegit).
> refactor: wrap system operations in a `System` object

- packages/matchers/src/__tests__/utils/builders.ts
- packages/matchers/src/__tests__/utils/parse/js.ts
These are always on by default with `@codemod/parser`.
> refactor: remove unneeded syntax flags

- packages/cli/package.json
- packages/core/package.json
- packages/matchers/package.json
- packages/parser/package.json
Lerna was considering this a "3rd-party" registry because the config was present at all. This should hopefully make lerna happier.
> chore(package): remove unnecessary `registry` config

- package.json
- packages/cli/package.json
- yarn.lock
Somehow the husky and lint-staged config stayed in packages/cli/package.json even though I moved it at some point.
> chore(package): really fix package sorting on commit

- package.json
- yarn.lock
We no longer support node v6, so there's no reason to use a version of ip-regex that does.
> chore(deps): unpin ip-regex

- packages/cli/package.json
- packages/core/package.json
I was wondering why I kept having the following warning when installing `codemod`:
```
warning "@codemod/cli > ts-jest@24.2.0" has unmet peer dependency "jest@>=24 <25"
```
It's because some packages declare `ts-jest` as a dependency and not a dev dependency.
This PR fixes it.
> fix: put ts-jest in devDependencies

- packages/cli/test/.mocharc.yml
- packages/cli/test/mocha.opts
This silences the warning about `mocha.opts` being deprecated.
> test: configure mocha correctly

- packages/cli/README.md
- packages/cli/src/Config.ts
- packages/cli/src/Options.ts
- packages/cli/src/index.ts
- packages/cli/test/cli/CLITest.ts
- packages/cli/test/fixtures/plugin/append-options-string.ts
- packages/cli/test/unit/OptionsTest.ts
With this users can do e.g. `codemod -p my-plugin -o @opts1.json -p my-plugin2 -o @opts2.json …` and have `opts1.json` be used for `my-plugin`'s options and `opts2.json` be used for `my-plugin2`'s options. Previously users had to specify the name of the plugin (or its file basename) when assigning options. Now the CLI can infer it based on argument position.
This preserves the feature of using the declared plugin name, but fails gracefully if doing so throws an exception. The downside is that this feature can, if the plugin instantiation throws, silently fail for reasons that are not clear. I think this trade-off is probably worth it.
Closes #686
cc @RIP21
> feat: allow assigning options to plugin positionally

- package.json
- packages/cli/package.json
- packages/core/package.json
- packages/matchers/examples/convert-static-class-to-named-exports.ts
- packages/matchers/package.json
- packages/matchers/src/matchers.ts
- packages/parser/package.json
- packages/parser/src/__tests__/test.ts
- packages/parser/src/options.ts
- yarn.lock
In babel v7.15.0 the "hack"-style pipeline operator was added which made the "smart" proposal deprecated. Additionally, there's now conflict between "smart"/"hack" pipes and "hash"-style records & tuples.
So now we default to the "minimal" pipeline operator proposal and ensure we don't add any conflicting plugins to an existing list.
Refs https://github.com/decaffeinate/decaffeinate/issues/2407
> fix(parser): support babel with "hack"-style pipes

- package.json
- packages/cli/jest.config.js
- packages/cli/package.json
- packages/core/jest.config.js
- packages/core/package.json
- packages/matchers/jest.config.js
- packages/matchers/package.json
- packages/parser/jest.config.js
- packages/parser/package.json
- yarn.lock
We no longer use it for transforming `.ts` files for use with Jest, so there's no need to keep it.
> chore(dev-deps): remove `ts-jest`

- README.md
Just specifying the start year is sufficient and less of a maintenance burden.
> docs: remove end of year range

- packages/matchers/README.md
* updating the docs to use the correct identifier name in the deep matches section example
> docs(matchers): correcting identifier name

- packages/cli/CHANGELOG.md
- packages/cli/__tests__/unit/InlineTransformer.test.ts
- packages/cli/package.json
- packages/cli/src/CLIEngine.ts
- packages/cli/src/Config.ts
- packages/cli/src/InlineTransformer.ts
- packages/cli/src/Options.ts
- packages/cli/src/index.ts
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/AllSyntaxPlugin.ts
- packages/core/src/index.ts
- packages/matchers/CHANGELOG.md
- packages/matchers/package.json
- packages/parser/CHANGELOG.md
- packages/parser/package.json
- packages/parser/src/index.ts
- packages/parser/src/options.ts
This allows directly specifying parser plugins to include, which may override the default plugins used.
Refs #899
> feat(cli): add `--parser-plugins` option

- packages/matchers/package.json
- packages/matchers/src/utils/match.ts
- packages/matchers/src/utils/matchPath.ts
The built package had types with an import specifier containing `../../src/matchers`. However, since `src` was the build root directory it does not appear in the final output structure. This rendered the import specifier invalid, breaking the types for the `match` and `matchPath` utilities. The fix was to use the correct shortest relative path.
Fixes #898
> fix(matchers): ensure package types work

- packages/matchers/README.md
- packages/matchers/jest.config.js
- packages/matchers/package.json
- packages/matchers/src/__tests__/matchers.test.ts
- packages/matchers/src/__tests__/nodesEquivalent.test.ts
- packages/matchers/src/matchers/fromCapture.ts
- packages/matchers/src/utils/nodesEquivalent.ts
Add support for matching nodes using `fromCapture`, which enables more natural captures like this:
```ts
const id = m.capture(m.identifier())
const idPlusIdMatcher = m.binaryExpression('+', id, m.fromCapture(id))
```
Refs #898
> feat(matchers): `fromCapture` structural matches

- packages/matchers/README.md
- packages/matchers/examples/convert-qunit-assert-expect-to-assert-async.ts
- packages/matchers/examples/convert-static-class-to-named-exports.ts
This finishes converting the examples to use structural matching with `fromCapture`.
Refs #904
> docs: update examples

- packages/matchers/package.json
- packages/matchers/src/__tests__/matchers.test.ts
- packages/matchers/src/matchers/or.ts
When I moved away from default exports I neglected to update these exports so only the generic `or` declaration was used.
> fix(matchers): correct `or` types

- packages/parser/package.json
- packages/parser/src/__tests__/test.ts
- packages/parser/src/options.ts
- packages/utils/src/builders.ts
Something about enabling the `placeholders` parser plugin causes parse errors when a TypeScript `abstract` class method is encountered. I'm not sure why, but this fixes it by disabling the `placeholders` parser plugin by default. It can still be enabled by passing it explicitly.
Closes #917
> fix: ensure TS abstract classes parse correctly
